# Generated by Django 3.1.3 on 2020-11-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_health_status_spo2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health_status',
            old_name='spo2',
            new_name='spO2',
        ),
    ]
