# Generated by Django 3.1.3 on 2020-11-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20201126_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_status',
            name='bpm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
